alias ls='ls -l --color=auto'
alias la='ls -a'
alias l='ls'
alias mkdir='mkdir -pv'

alias grep='grep --color=auto'
alias ..='cd ..'

uu(){
    if [[ -z "$TMUX" ]]; then
        if [ "$OS" = "Linux" ] && [ "$DISTRO" = "Debian" ]; then
            tmux new -s packageManager 'sudo apt update && sudo apt upgrade && sudo apt autoremove; zsh'
        elif [ "$OS" = "Linux" ] && [ "$DISTRO" = "Arch" ]; then
            tmux new -s packageManager 'sudo pacman -Syy && sudo pacman -Syu; zsh'
        fi
    else
        if [ "$OS" = "Linux" ] && [ "$DISTRO" = "Debian" ]; then
            sudo apt update && sudo apt upgrade && sudo apt autoremove
        elif [ "$OS" = "Linux" ] && [ "$DISTRO" = "Arch" ]; then
            sudo pacman -Syy && sudo pacman -Syu; zsh
        fi
    fi
}
alias pi="sudo pacman -S"
alias ai="sudo apt update && sudo apt install"

alias g='git'
alias gc='g commit'
alias gs='g status'
alias gd='g diff'

alias v='vim'
alias vali='v ~/.bash_aliases'
alias vth='v $ZSH_CUSTOM/themes/hellmen.zsh-theme'

alias tmux='TERM=xterm-256color tmux'
alias t='tmux'
alias ta='t attach'
alias tat='t attach -t'
alias tls='t list-sessions'
alias tn='t new-session -s'

alias ezsh='exec zsh'

alias sudo='sudo -E'

alias dot='cd ~/.dotfiles'
alias proj='cd ~/Dropbox/projects/'

alias psg="ps aux | grep -v grep | grep -i -e VSZ -e"
alias docker="sudo docker"

alias vle="sudo vim /opt/appdata/letsencrypt/config"
alias rle="docker restart letsencrypt"

alias vup="vim /home/petr/Dropbox/DockerCompose/docker-compose.yml"
alias rup="/home/petr/Dropbox/DockerCompose/up.sh"

randpw(){ < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-60};echo;}

