alias ls='ls -l --color=auto'
alias la='ls -a'
alias l='ls'
alias mkdir='mkdir -pv'

alias grep='grep --color=auto'
alias ..='cd ..'

alias uu='sudo apt update && sudo apt upgrade'
alias ai='sudo apt install'

alias g='git'
alias gc='g commit'
alias gs='g status'
alias gd='g diff'

alias v='vim'
alias vali='v ~/.bash_aliases'
alias vth='v $ZSH_CUSTOM/themes/hellmen.zsh-theme'

alias tmux='TERM=xterm-256color tmux'
alias t='tmux'
alias ta='t attach'
alias tat='t attach -t'
alias tls='t list-sessions'
alias tn='t new-session -s'

alias ezsh='exec zsh'

alias sudo='sudo -E'

alias dot='cd ~/.dotfiles'
