# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Linux specific
if [ "$(uname -s 2> /dev/null)" = "Linux" ]; then
    # Linuxbrew
    test -d ~/.linuxbrew && PATH="$HOME/.linuxbrew/bin:$HOME/.linuxbrew/sbin:$PATH"
    test -d /home/linuxbrew/.linuxbrew && PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"

    # WSL specific
    if [ ! -z "$USERPROFILE" ]; then
        cdpath+=(
        $USERPROFILE/Dropbox
        $USERPROFILE/Downloads
        )

        GOPATH=$USERPROFILE/go
    fi
fi
exec zsh
