alias ls='ls -l --color=auto'
alias la='ls -a'
alias l='ls'
alias mkdir='mkdir -pv'

alias grep='grep --color=auto'
alias ..='cd ..'

alias uu='sudo apt update && sudo apt upgrade'

alias g='git'
alias gc='g commit'
alias gs='g status'
alias gd='g diff'

alias vali='vim ~/.bash_aliases'
