#cd
# source .profile
[[ -e ~/.profile ]] && emulate sh -c 'source ~/.profile'

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="hellmen"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)


# User configuration
export ZSH_CUSTOM=~/.dotfiles/zsh_custom
source $ZSH/oh-my-zsh.sh

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

export EDITOR='vim'

unsetopt beep
unsetopt BG_NICE
export DISPLAY=:0
export DOTNET_CLI_TELEMETRY_OPTOUT=1

if [[ -z "$TMUX" ]] && [ "$SSH_CONNECTION" != "" ]; then
    tmux attach-session -t ssh_tmux || tmux new-session -s ssh_tmux
fi

if [[ "$PWD" == "/mnt/c/Users/pnedoma" ]]; then
    cd
fi

source "$HOME/.vim/bundle/gruvbox/gruvbox_256palette.sh"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

source /Users/pnedoma/.iterm2_shell_integration.zsh
source /Users/pnedoma/.config/kube.config

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

